"""
quiz_core.py - Core Quiz Functionality Module

This module handles all the backend data operations for the quiz application.
It manages loading questions from JSON files and saving quiz results.

AI Usage:
- Initial structure and pathlib usage was generated using Claude with the prompt:
  "Create a Python module that loads quiz questions from a JSON file and saves scores"
- Modified to fit my project's specific needs and file structure
- Comments were added by me to explain the purpose of each function
"""

import json
from pathlib import Path
from datetime import datetime

# Set up file paths using pathlib for cross-platform compatibility
# BASE_DIR gets the directory where this Python file is located
BASE_DIR = Path(__file__).resolve().parent

# DATA_DIR is where we store all quiz data (questions and scores)
DATA_DIR = BASE_DIR / "data"

# Create the data directory if it doesn't exist yet
# exist_ok=True means it won't error if the folder is already there
DATA_DIR.mkdir(exist_ok=True)

# Define the file paths for our data files
QUESTIONS_FILE = DATA_DIR / "quiz_questions.json"
SCORES_FILE = DATA_DIR / "score_history.json"


def load_questions(filename: Path = QUESTIONS_FILE):
    """
    Loads quiz questions from the JSON file.
    
    This function is called by app.py when someone starts the quiz.
    It reads the questions file and returns a list of question dictionaries.
    If the file doesn't exist, it automatically creates sample questions first.
    
    AI Usage: Basic file reading logic suggested by Claude, modified to handle
              FileNotFoundError by creating sample questions automatically.
    """
    try:
        # Open the file and read the JSON data
        with filename.open('r', encoding='utf-8') as file:
            data = json.load(file)
            # Return just the questions array from the JSON structure
            return data['questions']
    except FileNotFoundError:
        # If questions file doesn't exist, create it with sample questions
        print(f"Error: {filename} not found. Creating sample file...")
        create_sample_questions(filename)
        # Recursively call this function again now that the file exists
        return load_questions(filename)


def create_sample_questions(filename: Path = QUESTIONS_FILE):
    """
    Creates a sample quiz questions file with 5 default questions.
    
    This function only runs if the quiz_questions.json file doesn't exist.
    It creates a new file with sample trivia questions so the app has
    something to work with right away. Teachers/users can edit this file
    later to add their own questions.
    
    AI Usage: Sample question data structure was generated by Claude with prompt:
     "Generate 5 sample trivia questions in JSON format with multiple choice
      answers and explanations". I modified the explanations to be more detailed.
    """
    # Dictionary containing all the sample questions
    # Structure: questions array containing question objects
    sample_data = {
        "questions": [
            {
                "question": "What is the capital of France?",
                "options": {
                    "a": "London",
                    "b": "Berlin",
                    "c": "Paris",
                    "d": "Madrid"
                },
                "correct": "c",
                "explanation": "Paris is the capital and largest city of France."
            },
            {
                "question": "Which planet is known as the Red Planet?",
                "options": {
                    "a": "Venus",
                    "b": "Mars",
                    "c": "Jupiter",
                    "d": "Saturn"
                },
                "correct": "b",
                "explanation": "Mars is called the Red Planet because of rust on its surface, which gives it a reddish appearance."
            },
            {
                "question": "What is the largest ocean on Earth?",
                "options": {
                    "a": "Atlantic Ocean",
                    "b": "Indian Ocean",
                    "c": "Arctic Ocean",
                    "d": "Pacific Ocean"
                },
                "correct": "d",
                "explanation": "The Pacific Ocean is the largest and deepest ocean, covering approximately 63 million square miles."
            },
            {
                "question": "Who wrote 'Romeo and Juliet'?",
                "options": {
                    "a": "Charles Dickens",
                    "b": "William Shakespeare",
                    "c": "Jane Austen",
                    "d": "Mark Twain"
                },
                "correct": "b",
                "explanation": "William Shakespeare wrote 'Romeo and Juliet' around 1594-1596."
            },
            {
                "question": "What is the chemical symbol for gold?",
                "options": {
                    "a": "Go",
                    "b": "Gd",
                    "c": "Au",
                    "d": "Ag"
                },
                "correct": "c",
                "explanation": "The symbol Au comes from the Latin word 'aurum' meaning gold."
            }
        ]
    }
    
    # Write the sample data to a JSON file
    # indent=4 makes the file human-readable with nice formatting
    with filename.open('w', encoding='utf-8') as file:
        json.dump(sample_data, file, indent=4)
    print(f"Sample questions file created: {filename}")


def save_score_history(username, score, total, time_taken, breakdown):
    """
    Saves a user's quiz results to the score history file.
    
    This function is called by app.py after someone completes the quiz.
    It appends the new score to the existing score history (doesn't overwrite).
    Each quiz attempt is saved with a timestamp so we can track all attempts.
    
    AI Usage: Function structure generated by Claude with prompt:
     "Create a function to save quiz scores to JSON with timestamp".
     I added the percentage calculation and breakdown tracking myself.
    
    Note: This creates a log of ALL quiz attempts, so you can see improvement
          over time or compare scores between different users.
    """
    # Get current date and time in a readable format
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Calculate percentage score
    # The 'if total else 0' prevents division by zero errors
    percentage = (score / total) * 100 if total else 0

    # Create a dictionary with all the quiz result information
    record = {
        "timestamp": timestamp,
        "username": username or "Anonymous",  # Use "Anonymous" if no name given
        "score": score,
        "total": total,
        "percentage": round(percentage, 1),  # Round to 1 decimal place
        "time_taken": time_taken,
        "breakdown": breakdown,  # Detailed question-by-question results
    }

    # Load existing scores from file (if it exists)
    scores = []
    if SCORES_FILE.exists():
        try:
            with SCORES_FILE.open("r", encoding="utf-8") as f:
                scores = json.load(f)
        except json.JSONDecodeError:
            # If file is corrupted or empty, start with empty list
            scores = []

    # Add the new score to the list
    scores.append(record)

    # Write all scores back to the file
    with SCORES_FILE.open("w", encoding="utf-8") as f:
        json.dump(scores, f, indent=2)